version: '3'

services:
  db:
    image: 'postgres:11.1'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wic-dev
    ports:
      - 5432:5432
  app:
    build: 
      context: .
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - 'db'
    volumes:
      - .:/code
    ports:
      - 9000:9000
    environment:
      DATABASE_URL: "postgres://postgres:password@db"
      POSTGRES_PASSWORD: password
